### ISSUE TITLE
Purpose of the project?

### ISSUE THREAD

**Issue by shcheklein** [iterative/magnetic-tiles-defect#10]
Is there intention to integrate it into docs, online courses, etc? Is it made to be published as a blog post?

**Comment by casperdcl** [comment]
afaik to accompany conference talk, not sure what else though :thinking:

**Comment by alex000kim** [comment]
We'll also use it in the 2nd online course on https://learn.iterative.ai/

**Comment by shcheklein** [comment]
Got it, thanks! What will be the focus for the second course? (curious, could one of the existing examples fit?)

I think we need to codify the project then so that we can change / maintain it properly as we do all the example projects here - https://github.com/iterative/example-repos-dev, wdyt?

**Comment by alex000kim** [comment]
The target audience for the 2nd course is ML Engineers. Topics we'll cover are CI/CD for ML, exp management, deployment, monitoring, data and model registries. 
This demo project will serve as an example that ties (almost) everything together. 
Could you elaborate more on what you mean by codifying the project?

**Comment by shcheklein** [comment]
[experiment](https://github.com/iterative/example-dvc-experiments) can this one be expanded (to include CML)?

The benefits of that would be reusability, maintenance cost, and people getting something familiar as the come do /from docs to / from these lessons.

wdyt?

codification == writing a script like this https://github.com/iterative/example-repos-dev/blob/master/example-dvc-experiments/generate.bash

When you run it generates the whole example repo. This way you can iterate quickly on the repo and it's history. W/o something like this it might be very hard to maintain the project in the future - it history will become a bunch of updates to keep it in sync with changes in CML / DVC and the other tools.

**Comment by alex000kim** [comment]
Ok, that makes sense. Thanks!
I can put the codification of the project into my backlog for now as it doesn't seem to be urgent. Does that sound good?

**Comment by shcheklein** [comment]
@alex000kim it's not urgent, but it's a high priority and it is a requirement for all the projects that we are maintaining (docs, learn courses, doesn't apply to ad-hoc experiments, conference talks, blogs, etc). It's important to agree on this with the CSE team, make a ticket, and moving forward we should try to reuse (and improve as we go) our existing projects - that makes the whole ecosystem of docs way better :)

It would be awesome also if you could review the existing project that @iesahin was doing for the DVC docs (and beyond) and see what is missing there, can we use that one instead. Again, it means that we can improve the experience in multiple places simultaneously and save time going forward.

**Comment by alex000kim** [comment]
Sounds good. Ticket created - I will start working on this in the next sprint.

**Comment by iesahin** [comment]
We can work together in codification of this project. Please let me know your requirements, tags, branches, etc, so that the script can create a similar repository. If you're going to use this in the course, creating a Git tag for each lesson may be preferable. @alex000kim

**Comment by alex000kim** [comment]
discussions re: future plans for this project
- https://iterativeai.slack.com/archives/C02E3QJA6NB/p1658510155781829?thread_ts=1658509856.713659&cid=C02E3QJA6NB
- https://iterativeai.slack.com/archives/C039PTZCM39/p1658510602642239
