### ISSUE TITLE
The dvc/cml pipeline trick

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/magnetic-tiles-defect#13]
If you try to run a non changed pipeline (or already known by dvc) you will still run the CML reports

```yaml
# Create CML report
echo "## Metrics" >> report.md
dvc metrics show --md >> report.md
echo "## A few random test images" >> report.md
for file in $(ls data/test_preds/ |sort -R |tail -20); do cml-publish data/test_preds/$file --md >>report.md; done
cml send-comment --update report.md
```

to avoid that and even have the chance to report while local experimenting you can add this within the dvc yaml as another pipeline step. This way if the experiment is already known by dvc (nothing to do) the cml report wont happen either.

As mentioned the perk is that, because CML can work locally setting `--repo` `--token` `--head-sha` explicitly or setting env variables, you should be able to run this locally and save the reports in the SCM

**Comment by alex000kim** [comment]
Thanks, @DavidGOrtega . I can make a note about this, but I think it might not be necessary for this project because I am also working on a series of blog posts based on this. 
Adding this CML stage into the DVC pipeline will make it more confusing when explaining pipelines.
