### ISSUE TITLE
Experiment vs develop vs deploy

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/magnetic-tiles-defect#14]
- What is the difference between `experiment` and `develop` aside the latest deploys a model in staging? Why would I use one over the other?
 - Would be better if we deploy the model in `deploy` based on tags mechanism?

**Comment by alex000kim** [comment]
- `experiment` branch will be for ML experiments only. `develop` branch might contain changes to the web API.
- Agreed. I will work on adding this in.
