### ISSUE TITLE
Public s3 bucket

### ISSUE THREAD

**Issue by casperdcl** [iterative/magnetic-tiles-defect#7]
> `s3://alexkim-iterative-bucket/models/magnetic-tiles-defect/` is probably not accessible? we should be probably using the data registry? Not personal s3. And made it accessible via http as we do in all other examples.

(from @shcheklein)

**Comment by shcheklein** [comment]
Also, we should not be saving data into sandbox's S3 if we expect it to be used later. Everything in sandbox should be treated as ephemeral.

**Comment by alex000kim** [comment]
Replaced sandbox's bucket with `s3://dvc-public/remote/magnetic-tiles/`.
See https://github.com/iterative/magnetic-tiles-defect/commit/577f179c38c875424fdfb9bd697740e9ef811fa1
